name: Deploy to GitHub Pages

on:
  workflow_call:
    outputs:
      url:
        value: ${{ jobs.deploy.outputs.page_url }}
        description: "The URL of the deployed page"

  workflow_dispatch: {}

jobs:
  build-webgl:
    uses: ./.github/workflows/build-unity.yml
    secrets: inherit
    with:
      build_target_name: For_GitHub_Pages

  deploy:
    runs-on: ubuntu-latest
    needs: build-webgl

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Discord
        if: ${{ secrets.DISCORD_WEBHOOK_URL }} != ""
        run: |
            curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "ビルドが完了しました！ ${{ steps.deployment.outputs.page_url }}"
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
